### ISSUE TITLE
Issues with the HS login

### ISSUE THREAD

**Issue by fergusq** [hsci-r/finnish_media_scrapers#3]
I have issues with logging in using the following code:

```
>>> from selenium import webdriver
>>> driver = webdriver.Firefox()
>>> import src.finnish_media_scrapers.fetch as fetch
>>> fetch.prepare_session_hs(driver, "sensuroitu", "sensuroitu")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/iikka/Projektit/finnish-media-scraper/src/finnish_media_scrapers/fetch.py", line 19, in prepare_session_hs
    user = driver.find_element_by_id("username")
  File "/home/iikka/Projektit/finnish-media-scraper/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "/home/iikka/Projektit/finnish-media-scraper/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "/home/iikka/Projektit/finnish-media-scraper/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/iikka/Projektit/finnish-media-scraper/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="username"]
```

I use Firefox 89.0. The code above opens a graphical Firefox window and I see that it doesn't even open the login form.

My computer is very slow and it takes time for the browser to even load the main page of HS. Maybe this slowness is related to the error?

If I manually login to the browser, the actual process of fetching an article seems to work. However, it randomly fails on my computer sometimes. I will make a new issue after making more research on the conditions when it fails (if these fails are related to this library at all).

**Comment by jiemakel** [comment]
There may be two different issues here. One is that you are using the Firefox driver, which, unlike the Chrome driver, seems to not like clicking on elements that are behind other elements. In this case, this means we need to click on the link to accept cookies first before logging in. Second, you may indeed have problems due to slowness, as the login code did not include wait guards in trying to obtain the login form. I've now added both of these in b67c577fa93b48e00d5865b2cfe28394c76a9d9e, and would appreciate you retrying. 

(the maximum waits are 30 seconds, which are also the same for the actual fetching of the articles. I would hope these are enough, and that the problems you are seeing in the article fetching are not TimeoutExpections?)

**Comment by fergusq** [comment]
The HS login appears to be working now.

The fetching errors I were getting were indeed TimeoutExceptions from one of the `find_element_by_xpath` calls, but I haven't been able to reproduce them since then, they appear to be random.

Perhaps you could add an option to adjust the timeouts?

**Comment by jiemakel** [comment]
Option to alter maximum waiting time added. I'm closing this issue now, but feel free to reopen or file additional issues if problems persist.
